### ISSUE TITLE
Bugs/Improvements

### ISSUE THREAD

**Issue by sooraj1002** [techsavvyash/dynamo-prisma#12]
- [x] #13
- [x] #5 
- [x] Map Fieldnames with spaces #3 
- [x] #6 

Added the issues in the order of their priorities 

https://gist.github.com/sooraj1002/76437d0ac24d72ada0d0e9c77fd41b02

**Comment by Himasnhu-AT** [comment]
Used this function to check for model with no unique id

```ts
function ensureEachModelHasPrimaryKey(jsonData: Schema) {
  jsonData.schema.forEach((model) => {
    const primaryKeyFields = model.fields.filter((field) => field.isId);
    if (primaryKeyFields.length === 0) {
      console.error(`Model ${model.schemaName} does not have a primary key`);
      process.exit(1);
    }
  });
}
```

**Comment by Himasnhu-AT** [comment]
> * [x]  [Return success/error message so that package doesnt block the server #13](https://github.com/techsavvyash/dynamo-prisma/issues/13)
> * [ ]  [Schemas with no unique key, but valid postgres schemas fail #5](https://github.com/techsavvyash/dynamo-prisma/issues/5)
> * [ ]  Map Fieldnames with spaces [automatic mapping of field name with spaces  #3](https://github.com/techsavvyash/dynamo-prisma/issues/3)
> * [ ]  [Convert schema names with `-` to camel case, and return a warning saying this was done #6](https://github.com/techsavvyash/dynamo-prisma/issues/6)
> 
> Added the issues in the order of their priorities

**Comment by sooraj1002** [comment]
@Himasnhu-AT let's mark an issue once a PR is reviewed and merged.

**Comment by Himasnhu-AT** [comment]
okay, in the comments are issues, that are present in pr.

**Comment by Himasnhu-AT** [comment]
pr #17 is ready for review. this PR is handling all the 3 checkpoint issues covered. 😅 didn't create the new branch as I used main as the base, as it'll create merge conflicts

**Comment by sooraj1002** [comment]
Let's make different PRs for each issue.

- knowing how to resolve merge conflicts is necessary for working on any project of larger size as you wont always be the only person working on it

- it's easier to check at which point bugs, if any were introduced 

- much cleaner documentation of an issue and how it was resolved

**Comment by techsavvyash** [comment]
closing this out since it is good enough for dataset service right now.

**Comment by techsavvyash** [comment]
closing this out since it is good enough for dataset service right now.
