### ISSUE TITLE
if the input schema contains type is bad formatting, they should not be passed to schema.prisma as without any changes

### ISSUE THREAD

**Issue by sooraj1002** [techsavvyash/dynamo-prisma#4]
eg of the issue:

schema
```
 {
    fieldName: "Remarks",
    type: "string",
    description: "",
    maxLength: "",
    nullable: false,
    unique: false,
    vectorEmbed: false,
  },
```

creates the field `Remarks string` which is not a valid prisma field

**Comment by Himasnhu-AT** [comment]
This code block check or the type and it should be valid.
https://github.com/techsavvyash/dynamo-prisma/blob/upstream%2Fdemo/src%2Fchecks.ts#L21-L35

Will remove `tolowercase` then it should work

**Comment by Himasnhu-AT** [comment]
OUTPUT:  in case of error:

Checking for duplicates...
[
  'String',      'Int',
  'Float',       'Boolean',
  'DateTime',    'Decimal',
  'Json',        'Bytes',
  'Unsupported', 'User',
  'Post',        'Comment'
]
content in model Post is not a foreign key and not of type: "String",
            "Int",
            "Float",
            "Boolean",
            "DateTime",
            "Decimal",
            "Json",
            "Bytes",
            "Unsupported" or any other supported types
model:  {
  fieldName: 'content',
  type: 'string',
  description: 'Content of the post',
  maxLength: null,
  default: null,
  nullable: false,
  unique: false
}
