### ISSUE TITLE
Schemas with no unique key, but valid postgres schemas fail

### ISSUE THREAD

**Issue by sooraj1002** [techsavvyash/dynamo-prisma#5]
a schema like the following should work:

```json
{
    "schemaName": "test01",
    "fields": [
        {
            "fieldName": "Crop",
            "type": "VARCHAR",
            "description": "",
            "maxLength": "",
            "nullable": false,
            "unique": false,
            "vectorEmbed": false
        }
    ],
    "description": "Schema for seed treating materials data with details of each order"
}
 ```

**Comment by sooraj1002** [comment]
even with a unique key, package fails to update the prisma.schema in a NestJS service

![image](https://github.com/techsavvyash/dynamo-prisma/assets/91770496/afcafe4e-ec7b-4b9f-8912-e52fc542cdf9)

**Comment by Himasnhu-AT** [comment]
Used this function to check for model with no unique id

```ts
function ensureEachModelHasPrimaryKey(jsonData: Schema) {
  jsonData.schema.forEach((model) => {
    const primaryKeyFields = model.fields.filter((field) => field.isId);
    if (primaryKeyFields.length === 0) {
      console.error(`Model ${model.schemaName} does not have a primary key`);
      process.exit(1);
    }
  });
}
```

**Comment by Himasnhu-AT** [comment]
> even with a unique key, package fails to update the prisma.schema in a NestJS service
> 
> ![image](https://github.com/techsavvyash/dynamo-prisma/assets/91770496/afcafe4e-ec7b-4b9f-8912-e52fc542cdf9)
> 


Currently only `id` is considered for referencing fields in dB. Will add `unique` to it too

**Comment by sooraj1002** [comment]
lets change it from `field.isId` to `field.unique`

**Comment by sooraj1002** [comment]
also, lets  figure out a way to have models without a unique field, as many of the tables we will be creating might not have it, and still be valid postgres tables

**Comment by Himasnhu-AT** [comment]
> also, lets  figure out a way to have models without a unique field, as many of the tables we will be creating might not have it, and still be valid postgres tables

Will be little tricky. We can add another optional fields in model, which let the function know to skip table for check of unique fields

**Comment by sooraj1002** [comment]
that check should happen at the level of dynamo prisma to ensure that a model gets created if it is supported in a database

**Comment by sooraj1002** [comment]
this seems to be an open issue with prisma itself 

https://github.com/prisma/prisma/issues/7944

**Comment by techsavvyash** [comment]
referenced commit fixes the issue. We add a `dummy_id` field in the schema in case no unique field is present.

**Comment by Himasnhu-AT** [comment]
> referenced commit fixes the issue. We add a `dummy_id` field in the schema in case no unique field is present.

Okay. So like it'll creat a field with 
` id String @default(uuid())`
Or any improvement to it?
